### ISSUE TITLE
Download link is invalid

### ISSUE THREAD

**Issue by suwoncjh** [bidishasharma/RSL2019.github.io#1]
Hi, thanks for sharing the RSL2019 dataset.

I found that the download link is invalid.

(https://mynbox.nus.edu.sg/userportal/?v=4.4.3#/shared/public/gxN69HITevORE3rl/c8ae5934-74ce-4a12-ac19-b5fdef477060)

Could you provide another download link?

**Comment by bidishasharma** [comment]
The download link has been changed to  https://zenodo.org/record/4925958#.YMrwiSYRXCJ

**Comment by suwoncjh** [comment]
Thanks!
